/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ludoxi
 */
public class Pizzaria extends javax.swing.JFrame {
    float total = 0;
    String x = "";
    String y = "";
    float mult = 0;
    String j= "";

    /**
     * Creates new form Pizzaria
     */
    public Pizzaria() {
        initComponents();
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        ch = new javax.swing.JCheckBox();
        t = new javax.swing.JCheckBox();
        ca = new javax.swing.JCheckBox();
        p = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Pizza1 = new javax.swing.JComboBox<>();
        Coberturas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b.setText("Bacon");
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        c.setText("Cebola");
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        ch.setText("Champignon");
        getContentPane().add(ch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        t.setText("Tomate");
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        ca.setText("Catupiry");
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        p.setText("Presunto");
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel8.setText("Pizzas de x + cobertura y");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 560, 65));

        jLabel9.setText("0");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Comprar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        Pizza1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NENHUMA", "PEPPERONI", "MUSSARELA", "SUPREME" }));
        getContentPane().add(Pizza1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 30));

        Coberturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIVIDUAL", "REGULAR", "FAMILIA" }));
        getContentPane().add(Coberturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setText("ESCOLHA SUA PIZZA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setText(" Tamanho");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, 20));

        jLabel5.setText(" COBERTURAS EXTRAS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"PEPPERONI", "R$        15.00", "R$        27.00", "R$        33.00"},
                {"MUSSARELA", "R$        12.00", "R$        21.60", "R$        26.40"},
                {"SUPREME", "R$        17.00", "R$        30.60", "R$        37.40"}
            },
            new String [] {
                "SABOR", "INDIVIDUAL", "REGULAR", "FAMILIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 340, 80));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"BACON", "R$                                       2.00"},
                {"CEBOLA", "R$                                       1.50"},
                {"CHAMPIGNON", "R$                                       2.50"},
                {"TOMATE", "R$                                       1.00"},
                {"CATUPIRY", "R$                                       3.00"},
                {"PRESUNTO", "R$                                       2.50"}
            },
            new String [] {
                "COBERTURAS", "PREÇO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 340, 130));

        jButton3.setText("Novo pedido");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 30, 10));

        jLabel4.setText(" Sabor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pizza = Pizza1.getSelectedItem().toString();
        String cob = Coberturas.getSelectedItem().toString();
        
        
        if(pizza == "PEPPERONI"){          
            total = 15 ;
            x = "Pizza de Pepperoni ";
            if (cob == "INDIVIDUAL"){
            x += "Individual ";
            }
            if(cob == "REGULAR"){ 
            total += 12;
            x += " Regular ";
            }
            if(cob == "FAMILIA"){ 
                total += 18;
            x += " Família ";        
        }
        }
        if (pizza == "MUSSARELA") {
            total = 12;
            x = "Pizza de Mussarela ";
            if (cob == "INDIVIDUAL"){
            x += "Individual ";
            }
            if(cob == "REGULAR"){ 
            total += 9.6;
            x += " Regular ";
            }
            if(cob == "FAMILIA"){ 
            total += 14.4;
            x += " Família ";
        
        }
        }
        if (pizza == "SUPREME"){
            total = 17;
            x = "Pizza Supreme ";
            if (cob == "INDIVIDUAL"){
            x += "Individual ";
            }
            if(cob == "REGULAR"){ 
            total += 13.6;
            x += " Regular ";
            }
            if(cob == "FAMILIA"){ 
            total += 20.4;
            x += " Família ";
        
        }
        }

        if (b.isSelected()){
            total += 2;
            y += "+ Cobertura de Bacon ";    
        }
        
        if (c.isSelected()){
            
            total += 1.5;
            y += "+ Cobertura de Cebola ";
            
        }
        
        if (ch.isSelected()){           
            total += 2.5;
            y += "+ Cobertura de Champignon ";         
        }
        if (t.isSelected()){            
            total += 1;
            y += "+ Cobertura de Tomate ";           
        }
        if (ca.isSelected()){          
            total += 3;
            y += "+ Cobertura de Catupiry ";            
        }
        if (p.isSelected()){           
            total += 2.5;
            y += "+ Cobertura de Presunto ";            
        }
        if(pizza == "NENHUMA"){
            jLabel8.setVisible(true);
            jLabel8.setText("Selecione um sabor de pizza!");
        }else{
            jLabel9.setText("O total é: R$ " + total);
            jButton2.setVisible(true);
            jButton1.setVisible(false);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jButton3.setVisible(true);        
            jLabel8.setText("<html>"+x + y+ "</html>" );       
            total = 0;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        total = 0;
        b.setSelected(false);
        c.setSelected(false);
        ca.setSelected(false);
        ch.setSelected(false);
        t.setSelected(false);
        p.setSelected(false);
        Pizza1.setSelectedItem("NENHUMA");
        x = "";
        y = "";
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jButton2.setVisible(false);
        jButton1.setVisible(true);
        jButton3.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel8.setText("Obrigado e volte sempre!");
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Coberturas;
    private javax.swing.JComboBox<String> Pizza1;
    private javax.swing.JCheckBox b;
    private javax.swing.JCheckBox c;
    private javax.swing.JCheckBox ca;
    private javax.swing.JCheckBox ch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JCheckBox p;
    private javax.swing.JCheckBox t;
    // End of variables declaration//GEN-END:variables
}
